// 知识库管理相关组件导出
export { default as SearchToolbar } from './SearchToolbar.vue'
export { default as SearchToolbarEnhanced } from './SearchToolbarEnhanced.vue'
export { default as SearchStatusBar } from './SearchStatusBar.vue'
export { default as IntegratedToolbar } from './IntegratedToolbar.vue'
export { default as SortFilterBar } from './SortFilterBar.vue'
export { default as KnowledgeBaseSidebar } from './KnowledgeBaseSidebar.vue'
export { default as KnowledgeBaseList } from './KnowledgeBaseList.vue'
export { default as AdvancedSearchDialog } from './AdvancedSearchDialog.vue'
export { default as VectorSearchDialog } from './VectorSearchDialog.vue'
export { default as KnowledgeBaseFormDialog } from './KnowledgeBaseFormDialog.vue'
export { default as CreateSubjectDialog } from './CreateSubjectDialog.vue'
export { default as DocumentUploadDialog } from './DocumentUploadDialog.vue'
export { default as AIQuestionGenerationDialog } from './AIQuestionGenerationDialog.vue'

// 其他现有组件
export { default as DocumentManagement } from './DocumentManagement.vue'
export { default as KnowledgePointManagement } from './KnowledgePointManagement.vue'
export { default as GeneratedQuestions } from './GeneratedQuestions.vue'
export { default as BatchUploadDialog } from './BatchUploadDialog.vue'
export { default as ImportQuestionDialog } from './ImportQuestionDialog.vue'
export { default as DocumentPreviewDialog } from './DocumentPreviewDialog.vue'
export { default as QuestionPreviewDialog } from './QuestionPreviewDialog.vue'
export { default as KnowledgePointDetailDialog } from './KnowledgePointDetailDialog.vue'
export { default as AddEditKnowledgePointDialog } from './AddEditKnowledgePointDialog.vue'
export { default as AddEditQuestionDialog } from './AddEditQuestionDialog.vue'
export { default as RelationManagementDialog } from './RelationManagementDialog.vue'
export { default as OrganizeDialog } from './OrganizeDialog.vue'
export { default as PracticeModeDialog } from './PracticeModeDialog.vue'
export { default as AIExtractDialog } from './AIExtractDialog.vue'
export { default as ProcessingProgressDialog } from './ProcessingProgressDialog.vue'
export { default as DocumentProcessingProgress } from './DocumentProcessingProgress.vue'
export { default as KnowledgeBaseSettings } from './KnowledgeBaseSettings.vue'
